name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Only works with v2
      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.24.0'
#          channel: 'stable'
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /miniapp/
#          webRenderer: canvaskit
      - run: flutter --version